class ZabbixApi
  class Events < Basic
    # The method name used for interacting with Events via Zabbix API
    #
    # @return [String]
    def method_name
      'event'
    end

    # The id field name used for identifying specific Event objects via Zabbix API
    #
    # @return [String]
    def identify
      'name'
    end

    # Events are generated by the server and cannot be written through the API: the event
    # API provides only event.get and event.acknowledge.
    [:create, :delete, :update, :create_or_update, :get_or_create].each do |unsupported|
      define_method(unsupported) do |*|
        raise ApiError.new("Events##{unsupported} is not supported: the Zabbix event API only provides event.get and event.acknowledge")
      end
    end
  end
end
